os: linux
dist: bionic
language: python

services:
  - docker

jobs:
  include:
    - stage: Docker
      if: branch = master
      script:
           - sudo apt-get update
           - make docker-build
           - make docker-run
           - docker ps -a
           - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           - docker tag docker-zmq-pub  openvinoincluit/cloudconnector:latest
           - docker push openvinoincluit/cloudconnector:latest
           - make docker-stop
           - make docker-remove
           - docker images
           - docker system prune -a -f

    - stage: Validation
      if: branch = master
      script:
           - docker pull openvinoincluit/cloudconnector:latest
           - echo 'The Pipeline was validated!!!!'