# OpenVino Cloud - Connector
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title: Table of Contents

https://travis-ci.org/github/incluit/OpenVino-Cloud-Connector[image:https://travis-ci.org/github/incluit/OpenVino-Cloud-Connector.svg?branch=master[Build
Status]]
https://sonarcloud.io/dashboard?id=incluit_OpenVino-Cloud-Connector[image:https://sonarcloud.io/api/project_badges/measure?project=incluit_OpenVino-Cloud-Connector&metric=alert_status[Sonarcloud
Status]]


toc::[]

== Introduction

This project will received messajes from the queue and will send them to the AWS Kivana dashBoard.

== Bussines Logic

This Microservice will receive the alarms that are being generate by Blindspot and it will send them directly to the cloud.

== Prerequisites

This Microservice Runs on any Operative System, for any test we recommend Ubuntu in his latest version.

=== Hardware

The Microservice will run in any Device that can support an OS.

=== Software

The Microservice is written in Python so we need to any OS that support this language.

=== Checks

At this point you only need to ensure that you have an OS running with Python and Docker inside.

== Building

=== Basic Build

**1.** Clone the repository at desired location:

[source,bash]
----
git clone git@github.com:incluit/OpenVino-Cloud-Connector.git
----

**2.** Change to Main Folder of this Project:

[source,bash]
----
cd OpenVino-Cloud-Connector
----

**3.** Runs the following scripts:

[source,bash]
----
# Start the client process
python /app/src/client/zmqclient.py
----

=== Build with Docker

==== Prerequisites

* Docker. To install on Ubuntu, run:

[source,bash]
----
sudo snap install docker

sudo groupadd docker

sudo usermod -aG docker $USER
----

==== Installation

**1.** Clone the repository at desired location:

[source,bash]
----
git clone git@github.com:incluit/OpenVino-Cloud-Connector.git
----

**2.** Change to the top git repository:

[source,bash]
----
cd OpenVino-Cloud-Connector
----

**3.** Build the docker:
[source,bash]
----
make docker-build
----

=== Build in DockerHub
The master brach of this repository is built in Docker Hub:

https://hub.docker.com/r/openvinoincluit/cloudconnector

You can pull the Alert-Manager Docker image using:

----
docker pull openvinoincluit/cloudconnector
----

== Usage

=== Run With Docker

----
docker run -d --name docker-pub-server --network host -t docker-zmq-pub
----

=== Put Messages in the QUEUE
----
Only with Alert-Manager Microservice Running on the same machinne.

http://localhost:5000/piq/?param="Message to put in the QUEUE"
----

== Docker Options

* View logs file inside Container (Only Linux System)
[source,bash]
----
docker exec -it docker-cloud-connector cat /app/logs/subscriber.log
----

* Stop the docker container
[source,bash]
----
make docker-stop
----

* Remove the docker container
[source,bash]
----
make docker-remove
----