# OpenVino Cloud - Connector
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title: Table of Contents

https://travis-ci.org/incluit/OpenVino-Cloud-Connector[image:https://travis-ci.org/incluit/OpenVino-Cloud-Connector.svg?branch=master[Build
Status]]
https://sonarcloud.io/dashboard?id=incluit_OpenVino-Cloud-Connector[image:https://sonarcloud.io/api/project_badges/measure?project=incluit_OpenVino-Cloud-Connector&metric=alert_status[Sonarcloud
Status]]


toc::[]

== Introduction

This project will received messajes from the queue and will send them to the AWS Kivana dashBoard.

== Bussines Logic

This Microservice will receive the alarms that are being generate by Blindspot and it will send them directly to the cloud.

== Prerequisites

This Microservice Runs on any Operative System, for any test we recommend Ubuntu in his latest version.

=== Hardware

The Microservice will run in any Device that can support an OS.

=== Software

The Microservice is written in Python so we need to any OS that support this language.

=== Checks

At this point you only need to ensure that you have an OS running with Python and Docker inside.

== Building

=== Build with Docker

==== Prerequisites

* Docker. To install on Ubuntu, run:

[source,bash]
----
sudo snap install docker

sudo groupadd docker

sudo usermod -aG docker $USER
----

==== Installation

**1.** Clone the repository at desired location:

[source,bash]
----
git clone git@github.com:incluit/OpenVino-Cloud-Connector.git
----

**2.** Change to the top git repository:

[source,bash]
----
cd OpenVino-Cloud-Connector
----

**3.** Build the docker:
[source,bash]
----
make docker-build
make docker-run
----

== Usage

=== Put Messages in the QUEUE

For verifying how the CloudConnector receives event messages it will be mandatory that the user have the Alert-Manager Microservice up and running on the same machinne.
For installing and initiating Alert Manager Microservice, check the following link: https://github.com/incluit/OpenVino-Alert-Manager

**1.** For sending simulated events to the Alert Manager, open a browser and paste the following url:
----
http://localhost:5000/piq/?param=[Message to put in the QUEUE]
----

Also, you can send the event message through console terminal as follows:
----
culr http://localhost:5000/piq/?param=MessageToPutInTheQUEUE
----

**2.** For verifying all sent messages check the log file inside Container (Only Linux System) by executing the following command:
[source,bash]
----
docker exec -it docker-cloud-connector cat /app/logs/subscriber.log
----


== Docker Options

* Stop the docker container
[source,bash]
----
make docker-stop
----

* Remove the docker container
[source,bash]
----
make docker-remove
----
